[package]
name = "cli"
version = "0.3.1"
authors = ["Rick Fay <rickwithanh@gmail.com>"]
edition = "2021"
license = "GPL-2.0-or-later"

[dependencies]
log = "0.4.17"
settings = { path = "../settings" }
