name: build
on:
  workflow_dispatch:
  push:
jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { os: macos-latest , target: x86_64-apple-darwin, file: albw-randomizer }
          - { os: macos-latest , target: aarch64-apple-darwin, file: albw-randomizer }
          - { os: ubuntu-latest, target: x86_64-unknown-linux-musl, file: albw-randomizer }
          - { os: ubuntu-latest, target: aarch64-unknown-linux-musl, file: albw-randomizer }
          - { os: windows-latest, target: x86_64-pc-windows-gnu, file: albw-randomizer.exe }
          - { os: windows-latest, target: aarch64-pc-windows-msvc, file: albw-randomizer.exe }
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install musl dependencies
        if: ${{ matrix.platform.os == 'ubuntu-latest' }}
        run: sudo apt install -y musl-tools
      - name: Cargo build program
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--release --bin albw-randomizer"
          strip: true
      - name: Prepare zip file
        run: |
          mv target/${{ matrix.platform.target }}/release/${{ matrix.platform.file }} .
          mkdir generated
          touch generated/.keep
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.target }}
          path: |
            ${{ matrix.platform.file }}
            config.json
            generated
            presets
